### ISSUE TITLE
Important UI improvements

### ISSUE THREAD

**Issue by ggirotto** [olmps/Robin#20]
- Actions Toolbar is not fixed. When scrolling in the y-axis, the toolbar must be fixed on top.
- Use `svg` to change the icons colors on `DisclosureList`. Today we have two icons that only differ the icon color. We can use the <svg> tag to change the icon color programatically, the same way it's done on `Toolbar.tsx`

- Disable requests world map selection borders
<img width="1370" alt="Screen Shot 2020-05-11 at 16 37 24" src="https://user-images.githubusercontent.com/11745745/81604048-b2fc7d80-93a5-11ea-9b73-328091526c89.png">

- Request title is truncated on request details screen. Find a better solution
<img width="1371" alt="Screen Shot 2020-05-11 at 16 36 44" src="https://user-images.githubusercontent.com/11745745/81603994-9bbd9000-93a5-11ea-9ba4-4350e49c405a.png">

- Switch distribution presentation mode (chart)  with Stats presentation mode (icons container). Most of the requests are GET and POST, so the chart doesn't make sense. Using chart to represent the request stats will make the chart more useful. The request methods (GET, POST, DELETE, ...) can be presented as the stats are today.
<img width="1372" alt="Screen Shot 2020-05-11 at 16 38 43" src="https://user-images.githubusercontent.com/11745745/81604186-e3441c00-93a5-11ea-860f-adcace79333a.png">

- Add color to requests list icons (see if the UI fits better with color icons than just white)
<img width="309" alt="Screen Shot 2020-05-11 at 16 41 20" src="https://user-images.githubusercontent.com/11745745/81604451-45048600-93a6-11ea-9577-89f18eb447e6.png">

**Comment by matuella** [comment]
@ggirotto I think you could split each improvement in its own issue, as some of these doesn't seem so trivial
